stages:
  ingest:
    cmd: python -m src.data.ingest --input data/raw/water_potability.csv --output data/processed/water_potability.csv
    deps:
      - data/raw/water_potability.csv
      - src/data/ingest.py
    outs:
      - data/processed/water_potability.csv
  
  preprocess:
    cmd: python -m src.data.preprocess --params configs/params.yaml
    deps:
      - data/processed/water_potability.csv
      - src/data/preprocess.py
      - configs/params.yaml
    params:
      - configs/params.yaml:
          - preprocess.imputation_strategy
          - preprocess.scale
          - preprocess.test_size
          - preprocess.val_size
          - preprocess.random_state
    outs: 
      - data/processed/train.csv
      - data/processed/val.csv
      - data/processed/test.csv
      - data/processed/transformer.joblib
  
  train:
    cmd: python -m src.models.train --params configs/params.yaml
    deps:
      - data/processed/train.csv
      - data/processed/val.csv
      - src/models/train.py
      - configs/params.yaml
    params:
      - configs/params.yaml:
          - model.type
          - train.n_trials
          - train.cv_folds
    metrics:
      - artifacts/metrics/train_metrics.json:
          cache: false
    outs:
      - app/model_registry/model.joblib
  
  evaluate:
    cmd: python -m src.models.evaluate --params configs/params.yaml
    deps:
      - data/processed/test.csv
      - app/model_registry/model.joblib
      - src/models/evaluate.py
      - configs/params.yaml
    params:
      - configs/params.yaml:
          - evaluate.threshold
    metrics:
      - artifacts/metrics/test_metrics.json:
          cache: false
    plots:
      - artifacts/plots/roc_curve.png:
          cache: false
      - artifacts/plots/confusion_matrix.png:
          cache: false


