version: '3.8'

services:
  mlflow-db:
    image: postgres:13
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mlflow123}
    volumes:
      - mlflow-db-data:/var/lib/postgresql/data
    networks:
      - mlflow-network
    restart: unless-stopped

  mlflow-server:
    image: python:3.9-slim
    depends_on:
      - mlflow-db
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:${POSTGRES_PASSWORD:-mlflow123}@mlflow-db:5432/mlflow
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=s3://${S3_BUCKET}/mlflow-artifacts
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION:-us-east-1}
    ports:
      - "5000:5000"
    networks:
      - mlflow-network
    restart: unless-stopped
    command: >
      bash -c "
        pip install mlflow[extras] psycopg2-binary boto3 &&
        mlflow server
        --backend-store-uri postgresql://mlflow:${POSTGRES_PASSWORD:-mlflow123}@mlflow-db:5432/mlflow
        --default-artifact-root s3://${S3_BUCKET}/mlflow-artifacts
        --host 0.0.0.0
        --port 5000
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mlflow-db-data:

networks:
  mlflow-network:
    driver: bridge