name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # - name: Lint and Test
      #   run: |
      #     pytest -q
      - name: DVC repro 
        run: |
          dvc --version
          dvc repro -q || echo "DVC repro skipped"

          

